---
- name: Ensure some directories under $HOME
  file: path={{ ansible_env.HOME }}/{{ item.path }} state=directory mode={{ item.mode }}
  with_items:
    - { path: 'tmp',      mode: '0755' }
    - { path: 'gitrepos', mode: '0755' }
    - { path: 'my',       mode: '0755' }
    - { path: 'Vagrant',  mode: '0755' }
    - { path: '.ssh',     mode: '0700' }

