- hosts: 127.0.0.1
  connection: local
  become: yes
  become_method: sudo
  tasks:
    - include: tasks/common.yml
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - include: tasks/common.yml
